### ISSUE TITLE
Release for Composer

### ISSUE THREAD

**Issue by jakubmikita** [overclokk/minimum-requirements#3]
Hi, could you make a new release of the lib?

Composer doesn't want to install it as it's in dev-master version which conflicts with default minimal-stability

**Comment by jakubmikita** [comment]
PS. When loaded via Composer it cannot boot, because no autoloader is available for this lib

**Comment by overclokk** [comment]
Hi @Kubitomakita 

> Hi, could you make a new release of the lib?

> Composer doesn't want to install it as it's in dev-master version which conflicts with default minimal-stability

Yes, I can, first I want to made some little code refactoring and then I'll make a new release.

> PS. When loaded via Composer it cannot boot, because no autoloader is available for this lib

You have to load this library manually because it has to load before all of your code to check PHP compatibility, minimum for 5.2, if you load the `Minimum_Requirements` with an autoloader it could be too late to make PHP check.

**Comment by overclokk** [comment]
New release 1.0.0 ready for composer.
